# Generated by Django 3.2.16 on 2022-11-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=4)),
                ('fname', models.CharField(max_length=64)),
                ('lname', models.CharField(max_length=64)),
                ('pnumber', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=96)),
                ('role', models.CharField(max_length=8)),
            ],
        ),
    ]
