# Generated by Django 3.2.16 on 2022-11-13 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='email',
            new_name='emailId',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='fname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='lname',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='pnumber',
            new_name='phone',
        ),
    ]
